import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Dashboard from "@/components/Dashboard";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="px-32 py-3">
          <Navbar />
          <Dashboard />
          <div className="mt-8">{children}</div>
        </div>
      </body>
    </html>
  );
}
